### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by M6D6M6A** [JodelRaccoons/jodel_api#17]
Hello,

wanted to write some tools but im getting always 401 'Unauthorized' no matter, what i do.

My Reversed Key: LqYAXCHLWvtvTEApLTOLPUVfpIjlbminpiOVNduh
Version: 7.24.2

**Comment by Unbrick** [comment]
Seems to me like your keys are somehow invalid. The following key currently works for me: 

```
swbBCdBLdtvSqgflkjyrvVwiVHMZSQDQzQWsPiMg
7.25.8
```

**Comment by M6D6M6A** [comment]
Hm strange, used Frida multiple Times, dont know what went wrong. How do you get the Version? I used the https://apkpure.com/de/jodel-hyperlocal-community/com.tellm.android.app and it says 7.24.2 for Android?
Thanks for the Help!

**Comment by Unbrick** [comment]
I downloaded the latest version from Google Play. I guess your HMAC key is already blacklisted.

Can you try out the key i provided? Does this one work for you?

**Comment by M6D6M6A** [comment]
It wont work for me with following code:
(downloaded recent jodel_api from this GitHub)

updated __init__.py (so it takes the local files):
`
from __future__ import (absolute_import, print_function, unicode_literals)

from .protos import mcs_pb2
from .protos import checkin_pb2
from .gcmhack import AndroidAccount
from .jodel_api import *
`

updated jodel_api.py:
`
...
class JodelAccount:
    post_colors = ['9EC41C', 'FF9908', 'DD5F5F', '8ABDB0', '06A3CB', 'FFBA00']

    api_url = "https://api.go-tellm.com/api{}"
    client_id = '81e8a76e-1e02-4d17-9ba0-8a7020261b26'
    secret = 'swbBCdBLdtvSqgflkjyrvVwiVHMZSQDQzQWsPiMg'.encode('ascii')
    version = '7.25.8'

    access_token = None
    device_uid = None
...
`

renamed Folder from jodel_api -> local_jodel_api and placed it with the test_jodel_api.py:
`
import local_jodel_api as jodel_api

lat, lng, city = 48.148434, 11.567867, "Munich"
j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)
print(j.get_account_data())
`

Will output:
`
Creating new account.
Creating account with data {'location': {'country': 'DE', 'city': 'Munich', 'loc_coordinates': {'lat': 48.148434, 'lng': 11.567867}, 'loc_accuracy': 15.457}, 'iid': 'Lulululululu', 'client_id': '81e8a76e-1e02-4d17-9ba0-8a7020261b26', 'registration_data': {'channel': '', 'referrer_id': '', 'campaign': '', 'feature': '', 'provider': 'branch.io', 'referrer_branch_id': ''}, 'device_uid': '80603b2d0bf50c5c4bb648885f6234a76f2a71d8d979ec34745427e0ec0674e9', 'language': 'de-DE'}
Traceback (most recent call last):
j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)
r = self.refresh_all_tokens(pushtoken, **kwargs)
raise Exception(resp)
Exception: (477, {'error': 'Signed request expected', 'metadata': None})
`

**Comment by Unbrick** [comment]
I just looked into the source. Seems to me like the [payload](https://github.com/JodelRaccoons/jodel_api/blob/9e8094d11b6f90dbbf7d13d85425f3a3b7430860/src/jodel_api/jodel_api.py#L151) sent to the server is the issue. Jodel changed the registration of new users on Android to a email based verification which currently this api does not support.


I'm currently trying to figure out how to recreate the user creation mechanism from the iOS version of the app, looks like the authentication mechanism is easier there. If all works out the API could be working again in a few days.

**Comment by Unbrick** [comment]
I updated the source, should work now again!
