### ISSUE TITLE
Feature request: implement hometown

### ISSUE THREAD

**Issue by springjools** [JodelRaccoons/jodel_api#18]
## Feature
def send_home_town(self, location, **kwargs):
    return self._send_request("PUT", "/v3/user/home", payload={"location": self._get_location_dict(self.lat, self.lng, self.city)}, **kwargs)
...
This end point could be useful. It seems that jodel is actively reverting votes, maybe they use location from IP-address to detect votes they don't want to keep. Setting a hometown could be a possible resolution.

Update on some rate limits: seems a 429 kicks in at 100 votes/minute instead of 200, but I think these are probably dynamic. They could also compare night-time traffic to day time one.

Also: about 75 - 80 % of requests normally succeed, the rest return 403 even in normal circumstances.

**Comment by Unbrick** [comment]
The implementation of the hometown feature should be fairly quickly done. Feel free to create a PR, otherwise i can add it in a future update.

Did you find out why Jodel is actively reverting votes?

**Comment by springjools** [comment]
I tried to add in the function in src/jodel_api, but it doesn't find it. Maybe I messed up. But so I haven't been able to test it yet.

I'm not sure they are, but one thing I noticed was that sometimes, when you have used the downvote/upvote function and you parse the return output, there is one votecount in the 'post' field and one outside of it. Sometimes those values don't match, but sometimes they do, indicating that the voting had no effect. But if you get the votecount of the same post from the parent post, then that will most of the time show the unvoted count. I think there is a delay for when the vote takes effect in the server. You can get this time from the last modified field. I think a succesful vote takes about 60 seconds to take effect.

**Comment by springjools** [comment]
The reverting votes could just be that I relied on the new votecount from the 'post' field and the values seemed reverrted when the post was updated from another source. But it seems that there have been jodel notifications sent out even if the vote counts have not changed, those notifications that say your post has xx number of votes.
