### ISSUE TITLE
Newly created accounts blocked on startup

### ISSUE THREAD

**Issue by springjools** [JodelRaccoons/jodel_api#19]
## Issue
Can someone verify this issue? I'm seeing newly created accounts as blocked. Happened since a couple of days I think. I could also be doing something wrong.

...

## Environment

If you're reporting a bug, please attach the output of the following commands:

```
$ pip3 show jodel_api
Name: jodel-api
Version: 1.2.11
Summary: Unoffical Python Interface to the Jodel API
Home-page: https://github.com/nborrmann/jodel_api
Author: Nils Borrmann
Author-email: n.borrmann@googlemail.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages/jodel_api-1.2.11-py3.8.egg
Requires: future, mock, protobuf, requests, varint
Required-by:
$ pip3 -V
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
$ python3 -V
Python 3.8.10
$ python3 -c "import jodel_api; print(jodel_api.JodelAccount.version); print(jodel_api.JodelAccount.secret)"
7.26
b'ITphnJSfuGskaTENCxRIPbiiaMScFRhycyZvFNaT'
```

**Comment by ttiasg** [comment]
Same on my end.

**Comment by springjools** [comment]
Old accounts still work. Also I noticed that they block accounts if there is too much activity (probably per ip), but the block isn't instantaneous; it can come after a delay of some minutes or hours.

**Comment by asZacJxca** [comment]
Whats the point of these useless projects?

**Comment by Unbrick** [comment]
@springjools @ttiasg I'll look into this in the coming days, maybe Jodel blocked accounts registered with iOS devices and verified using GCM but that is just a guess.

**Comment by asZacJxca** [comment]
@Unbrick Why bother? they will just keep patching it

**Comment by Unbrick** [comment]
@asZacJxca because it's quit good fun. It's like a cat and mouse game but on a technical level. Taking new obstacles given by Jodel improves my knowledge and my tooling. I even gives me the opportunity to develop own tools which can then be used in other projects. And as far as I know the guys at Jodel HQ are cool with it, so why not?

**Comment by asZacJxca** [comment]
@Unbrick Where can i read when they said that?

**Comment by Unbrick** [comment]
@asZacJxca sadly you can't, they told us (JodelRaccoons) so when we visited them in Berlin (back in the JodelXposed/JodelPatched times). If you have any more questions unrelated to this issue, feel free to hit me up on Telegram (@ubrick).

**Comment by springjools** [comment]
I also think it's fun and useful. Why are you following this issue @asZacJxca if you are not interested?

**Comment by Unbrick** [comment]
@springjools @ttiasg I just updated the keys to 7.28.1 (Android) with commit 465ec21229f33d33ef799b6ce2358bbba7539afe and the registration is working for me again. Can you verify this?

**Comment by ExTBH** [comment]
I still get the same error from last issue, am i doing something wrong? :(

![image](https://user-images.githubusercontent.com/84900328/147230604-8143f8ae-67ef-48db-a45a-1cb33462a1df.png)

**Comment by Unbrick** [comment]
@ExTBH can you please execute the following command?

```
python3 -c "import jodel_api; print(jodel_api.JodelAccount.version); print(jodel_api.JodelAccount.secret)"
```

**Comment by ExTBH** [comment]
i started a new venv and did pip install after i saw u updated it i will try clone it now

![image](https://user-images.githubusercontent.com/84900328/147231368-b430d6c8-0802-4620-9c66-de95942e3dac.png)

**Comment by Unbrick** [comment]
@ExTBH Sadly there is currently no version of this repo within the pip repositories so you need to clone it manually or install it using the following command: 

'''
pip3 install git+git://github.com/JodelRaccoons/jodel_api.git#egg=jodel-api
'''

**Comment by ExTBH** [comment]
It worked Thanks, 
sorry if i wasted your time im new i only know pip install 😄

**Comment by Unbrick** [comment]
@ExTBH No problem, glad i could help!

**Comment by springjools** [comment]
Hmm, I'm still getting blocked accounts. Did you try with:
`
>>> import jodel_api
>>> lat, lng, city = 48.148434, 11.567867, "Munich"
>>> j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)
>>> print(j.get_user_config()[1].get('user_blocked')
`

**Comment by ExTBH** [comment]
Im using the same account from 4 hours ago, i got the recent posts couple times, 
account not banned for me


`lat, lng, city, country = 26.215900, 50.538029, "Jidhafs",'Bahrain'`

**Comment by springjools** [comment]
Yes, maybe. I tried with different lon and lat and depending on those, you get banned too. Without a country variable.

**Comment by springjools** [comment]
The api works but depending on Lon and Lat, you may be banned.

**Comment by springjools** [comment]
Actually it wasn't the fact that IP has to match country, it was just a geoban. I tried a few degrees south and then the accounts didn't get banned
