### ISSUE TITLE
j.get_post_details_v3(post_id, skip=0)

### ISSUE THREAD

**Issue by springjools** [JodelRaccoons/jodel_api#22]
## Issue
j.get_post_details_v3(post_id, skip=0) seems to have changed. Now it returns:
* one list of dicts called 'details'
* one list of dicts called replies
* additional fields like these:
   'next': <13 digits>,
    'hasPrev': boolean,
    'remaining': int,
    'shareable': boolean,
    'readonly': boolean,
    'votable': boolean,
    'reboostable': boolean,
    'powers': list,
    'banned': boolean,
    'restrictions': list,
    'restricted': boolean,
    'muted': boolean,
    'postblock': boolean,
    'ads': list,
    'verifiedStatus': 'not_set',
    'canReceiveChatRequest': boolean
...

It seems that the skip parameter has no effect anymore, but the next parameter is too short to be a post_id. Not sure what it is.

## Environment

If you're reporting a bug, please attach the output of the following commands:

```
$ pip show jodel_api
$ pip -V
$ python -V
$ python -c "import jodel_api; print(jodel_api.JodelAccount.version); print(jodel_api.JodelAccount.secret)"
```

**Comment by springjools** [comment]
Edit: next is probably an unix timestamp, so maybe that should be fed to the "after" parameter, like on other endpoints.

**Comment by Unbrick** [comment]
Could you please include the requests and responses you got there? Did you record communication from the app to the jodel server or did you use the api directly?

**Comment by springjools** [comment]
I used the API directly.
