### ISSUE TITLE
Signed request expected

### ISSUE THREAD

**Issue by springjools** [JodelRaccoons/jodel_api#25]
## Issue
Api broken, probably needs to be updated for new version of jodel
...

## Environment

If you're reporting a bug, please attach the output of the following commands:

```
$ pip show jodel_api
$ pip -V
$ python -V
Python 3.8.10
$ python -c "import jodel_api; print(jodel_api.JodelAccount.version); print(jodel_api.JodelAccount.secret)"
7.35
b'rYKfoeKQOwMHtBNTrCgvXEvgJBdwAHeZJFVqsBYh'
```

**Comment by Unbrick** [comment]
You might want to try the following key (with Android client type):

Secret: KLznblPWytpbUKfDTBxHKpCpFQdrPIEGAyDFzstX
Version: 7.35.1

**Comment by springjools** [comment]
It works kind of, but I think there is some shadow banning involved. But maybe it works for someone else. But try this:
`
import jodel_api
lat, lng, city = 48.148434, 11.567867, "Munich"
 j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)
j.get_user_config()[1].get('user_blocked')
=> False
j.get_user_config()[1].get('user_blocked')
=> True
`
