### ISSUE TITLE
Broken functions/ feed is english only

### ISSUE THREAD

**Issue by ExTBH** [JodelRaccoons/jodel_api#27]
## Issue
Broken functions/ feed is english only, I've tested the below looks like a couple need fixes

```
j.get_posts_recent() -> Works //hmm shows english only
j.get_posts_popular() -> Works //english only
j.get_posts_discussed() -> Works // english only
j.get_pictures_recent() -> Works // english only
j.get_pictures_popular() -> Works // english only
j.get_pictures_discussed() -> Works // english only
j.get_my_pinned_posts() -> Works
j.get_my_voted_posts() -> Works, but returned some random posts from Germany
j.post_search() -> Works

j.create_post() -> Works
j.get_post_details_v3('<post_id>') -> Doesn't // (477, {'error': 'error', 'metadata': None})
j.upvote('<post_id>') -> Doesn't // (477, {'error': 'error', 'metadata': None}
j.downvote('<post_id>') -> Works // (200, {<Details>}
j.give_thanks('<post_id>') -> Probably Works // (403, {'error': 'Post is not a reply', 'metadata': None})
j.get_share_url('<post_id>') Works
j.pin('<post_id>') Works
j.unpin('<post_id>') Works
j.enable_notifications('<post_id>') Works
j.disable_notifications('<post_id>') Works
j.delete_post('<post_id>') Works but crash the program <json.decoder.JSONDecodeError: 
                            Expecting value: line 1 column 1 (char 0)> // line 129 in jodel_api.py probably 
                             tries to load emptry string // Check for status code 204

j.get_notifications() Works
j.get_notifications_new() Works
j.notification_read(post_id="<post_id>", notification_id="<not_id>") Doesn't // (500, {'error': 'Internal Server Error', 'metadata': None})

j.get_recommended_channels() Works
j.get_channel_meta() Wroks
j.follow_channel() probably Works // Same Error as j.delete_post('<post_id>')
j.unfollow_channel() Same above
```
```python
if resp.status_code == 204:
     return resp.status_code, 
```
should be added below https://github.com/JodelRaccoons/jodel_api/blob/26de3e31e90a21ce39caa3b05bb5ab571eb55c11/src/jodel_api/jodel_api.py#L118

for english feed ~~`Accept-Language: en-BH;q=1, ar-BH;q=0.9, hi-BH;q=0.8, zh-Hans-BH;q=0.7, en;q=0.6` this is used when refreshing the feed in the iPhone App, maybe a WildCard show fix it~~ Doesn't Work when adding it to headers in _send_request()

### Fixes
- [x] English Posts
- [x] Upvote
- [x] Empty response (204)
- [x] Post detailsv3
- [x] notification_read

**Comment by springjools** [comment]
Why does downvote work but not upvote? Did you try them the same way? For example, was one in the main channel and the other in some other channel? Sometimes they return 477 and explanation "channel not followed" even though it is.

**Comment by ExTBH** [comment]
just tired this, i picked a post from get_recent_posts(), opened it on my phone, upvoted -> nothing changed on phone, downvoted -> counter changed from 5 to 4 on phone, it was on main channel it is followed by default i think

```python
>>> j.upvote('62e888c6c43e9c680517670d')
(477, {'error': 'error', 'metadata': None})
>>> j.downvote('62e888c6c43e9c680517670d')
(200, {'post': {'message': 'the only downside 💔', 'updated_at': '2022-08-02T20:40:40.213Z', 'voted': 'down', 'pin_count': 1, 'notifications_enabled': False, 'image_approved': True, 'replier': 0, 'child_count': 23, 'post_id': '62e888c6c43e9c680517670d', 'discovered_by': 0, 'postblock': False, 'post_type': 'normal', 'reaction_counts': {}, 'reaction_ids': [], 'reaction_count': 0, 'used_reaction_ids': [], 'highlighted_until': None, 'vote_count': 4, 'got_thanks': False, 'super_thanks_count': 0, 'channel': 'Main', 'created_at': '2022-08-02T02:15:36.881Z', 'channels': {'5f8ebbb3fd37e500256f7a67': 'main'}, 'promoted': False, 'was_promoted': False, 'promoted_type': '', 'cta_type': 'normal', 'location': {'name': 'Zinj', 'loc_coordinates': {'lat': 0, 'lng': 0}, 'loc_accuracy': 0, 'country': 'BH', 'city': ''}, 'share_count': 0, 'user_handle': 'oj', 'view_count': 0, 'color': '338DF5', 'post_own': 'friend', 'distance': 2, 'image_url': '<url>', 'thumbnail_url': '<url>', 'media_source': 'camera', 'location_type': 'local', 'votable': True, 'children': []}, 'vote_count': 4})

```

**Comment by Unbrick** [comment]
I just pushed a commit (android_mail_auth branch) which should fix upvoting posts. Not sure about the other issues but could fix some of them too.

**Comment by Unbrick** [comment]
Just found out that one can select preferred languanges within the feed. I just added the method `j.set_user_language()` which should select all languages for the current user. Fetching posts afterwards should give all posts back.

**Comment by springjools** [comment]
Btw, did you notice that the distinct_id is always the same nowadays? Ie, it is not distinct. So when you refresh one account with this id, it works, but then when you refresh another with the same distinct_id, it becomes invalid and you get a 401 when trying to refresh the token with the first account.

**Comment by ExTBH** [comment]
Looks all work I've retested and added them to the end of the first post, don't think i missed anything. issue can be closed if you guys don't have more issues,

**Comment by Unbrick** [comment]
Awesome, thank you for reporting and testing. Closing this for now.
