### ISSUE TITLE
Not working, even with new secret

### ISSUE THREAD

**Issue by Greansilver** [JodelRaccoons/jodel_api#3]
After I used the script for the first time, I got the error message:

Exception: (477, {'error': 'Signed request expected', 'metadata': None})

After I read that the key is changed after few weeks, I reverse engineered the key, but if I set the parameters JodelAccount.secret = "ycuIucePbuyggMRCjhmbDEpraKcvvlirpqpAkJfG".enc... and JodelAccount.version = '5.80.0' (status 05.05.2020) then I still get the same error code, do I have to update more parameters, is this the wrong key or does it not work anymore?

- Windows 10

**Comment by Unbrick** [comment]
Hey there!

I just tried to reconstruct the issue and parsed the HMAC key by myself from the version 4.81.0.

With the version number 4.81.0 and the hmac key 

```
Derived key of length 40 from library, now decrypting it...
Got raw key array: [239, 210, 179, 176, 168, 201, 221, 31, 132, 37, 18, 25, 146, 98, 33, 47, 53, 21, 135, 110, 114, 232, 13, 56, 54, 96, 68, 150, 136, 101, 248, 53, 243, 73, 183, 16, 135, 204, 42, 177]
Got decrypted key: ycuIucePbuyggMRCjhmbDEpraKcvvlirpqpAkJfG
```

it works for me. Seems like you just messed up the version numbers :)

**Comment by Greansilver** [comment]
Thanks for the fast asnwer, working now!!!
How to find the correct version? Appstore saied 4.80.0...

**Comment by Unbrick** [comment]
I usually check on [ApkPure](https://apkpure.com/de/jodel-hyperlocal-community/com.tellm.android.app) for the latest version
