### ISSUE TITLE
How do I figure out if I’m banned?

### ISSUE THREAD

**Issue by Morphior** [JodelRaccoons/jodel_api#30]
## Issue

I am able to pin posts, get recommended posts, etc. Basically everything that’s read-only. But upvoting and posting don’t work as far as I can see (posts I make through the script don‘t show up in the app and upvotes are also not counted). I did see the message that accounts that use the iOS based authentication get banned immediately — how do I see if that’s the case? If I use the `create_post()` method, I get a status code 200 back, along with all the info about the post. But when I do `get_post_details()` on that post id, it shows that it’s an empty post.

## Environment

If you're reporting a bug, please attach the output of the following commands:

```
$ pip show jodel_api
Name: jodel-api
Version: 1.2.11
Summary: Unoffical Python Interface to the Jodel API
Home-page: https://github.com/nborrmann/jodel_api
Author: Nils Borrmann
Author-email: n.borrmann@googlemail.com
License: MIT
Location: /usr/lib/python3.10/site-packages/jodel_api-1.2.11-py3.10.egg
Requires: future, mock, protobuf, requests, varint
Required-by: 

$ pip -V
pip 22.2.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)

$ python -V
Python 3.10.5

$ python -c "import jodel_api; print(jodel_api.JodelAccount.version); print(jodel_api.JodelAccount.secret)"
7.51
b'YEKawcOEwzigovvWEFkBVWPIsgHhnIFmfMtfjYLS'
```

**Comment by B00TK1D** [comment]
@Morphior  What was your solution?  I am in a similar situation, I can call all ready functions and the create_post call seems to work, but then it doesn't show up on the feed.

**Comment by gusfringy1** [comment]
@B00TK1D have you found any fix to it I cannot post a comment or a reply too.
