### ISSUE TITLE
Disconnecting if running longer

### ISSUE THREAD

**Issue by Greansilver** [JodelRaccoons/jodel_api#4]
I wrote a script that gets the post details of a given post every second.
It works most of the time well but sometimes i get following error:
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

If you dont have a solution ill write a recurson loop to restart a new session and then go on, but would be cleaner without.

- Windows 10

**Comment by Unbrick** [comment]
I guess thats related to rate limiting, try using proxy's when making that many requests.

**Comment by Greansilver** [comment]
Thought so, but if i do a recursiv funktion like this:

```
    def set_save_location(self, _post_id, point):
        try:
            self.j.set_location(point["lat"], point["lng"], self.jodel_account["city"], country=None, name=None)
        except Exception as e:
            print(f"Error: {e}")
            self.j = jodel_api.JodelAccount(lat=self.jodel_account["lat"], lng=self.jodel_account["lng"], city=self.jodel_account["city"],
                            access_token=self.jodel_account["access_token"], expiration_date=self.jodel_account["expiration_date"],
                            refresh_token=self.jodel_account["refresh_token"], distinct_id=self.jodel_account["distinct_id"],
                            device_uid=self.jodel_account["device_uid"], is_legacy=True)
            self.set_save_location(_post_id, point)
```

instead of normally calling the function it works fine, if i would bew ratelimited i would expect a 403 "Access Denied"?

**Comment by Unbrick** [comment]
As far as I know (also got a few bots running) they enhanced the rate limiting due to ddos attacks. When making to many requests the ddos protection kicks in and just denies the requests

**Comment by Greansilver** [comment]
ok, will just double the wait time between two requests
