### ISSUE TITLE
Posted Images wont get displayed in the App

### ISSUE THREAD

**Issue by M6D6M6A** [JodelRaccoons/jodel_api#5]
If I only post a text, everything works as expected and the post is also displayed in my app with my main account.
If I now specify an imgpath, the post is created and I can see it with the API, but when I search for it in the app, I can't find it. I even posted it in an empty channel and on my mobile phone I get a message that no post has been made yet, you know why?

**Comment by Greansilver** [comment]
Looks like it does only display the img if its jpg?

**Comment by Unbrick** [comment]
I guess the image needs to be jpg but i would need to verify it manually. Does it work using jpg?

**Comment by M6D6M6A** [comment]
Jup, just use .jpg and everything should work fine
